version: '3'

services:
  transit-calendar:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: transit-calendar
    restart: unless-stopped
    user: root
    volumes:
      - transit_data:/app/data
    environment:
      # Database and log settings
      - DB_PATH=/app/data/transit-calendar.sqlite
      - LOG_FILE=/app/data/transit-calendar.log
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # Calendar settings
      - SOURCE_CALENDAR_URL=${SOURCE_CALENDAR_URL}
      - SOURCE_CALENDAR_USERNAME=${SOURCE_CALENDAR_USERNAME}
      - SOURCE_CALENDAR_PASSWORD=${SOURCE_CALENDAR_PASSWORD}
      - DESTINATION_CALENDAR_URL=${DESTINATION_CALENDAR_URL}
      - DESTINATION_CALENDAR_USERNAME=${DESTINATION_CALENDAR_USERNAME}
      - DESTINATION_CALENDAR_PASSWORD=${DESTINATION_CALENDAR_PASSWORD}

      # HERE API settings
      - HERE_API_KEY=${HERE_API_KEY}
      
      # Home location and transit defaults
      - HOME_ADDRESS=${HOME_ADDRESS}
      - DEFAULT_TRANSIT_MODE=${DEFAULT_TRANSIT_MODE:-transit}
      
      # Time settings
      - LOOK_FORWARD_DAYS=${LOOK_FORWARD_DAYS:-28}
      - CALENDAR_CHECK_INTERVAL=${CALENDAR_CHECK_INTERVAL:-15}
      - DAILY_UPDATE_TIME=${DAILY_UPDATE_TIME:-01:00}
      - MAX_TRANSIT_TIME_HOURS=${MAX_TRANSIT_TIME_HOURS:-3}

volumes:
  transit_data:
    external: false